version: 2
updates:

- package-ecosystem: 'github-actions'
  open-pull-requests-limit: 10
  directory: '/'
  schedule:
    interval: 'monthly'

- package-ecosystem: 'docker'
  open-pull-requests-limit: 10
  directory: '/'
  schedule:
    interval: 'monthly'

# - package-ecosystem: 'gomod'
#   open-pull-requests-limit: 10
#   directory: '/'
#   schedule:
#     interval: 'monthly'

# - package-ecosystem: 'cargo'
#   open-pull-requests-limit: 10
#   directory: '/'
#   schedule:
#     interval: 'monthly'
